version: "3.9"

services:
  mabel:
    image: python:3.12-slim
    container_name: mabel_python
    working_dir: /app
    volumes:
      - /home/joel/MAF/MabelPy:/app
    tty: true
    stdin_open: true
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: bash
